# Generated by Django 6.0.2 on 2026-03-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_filename',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
