# Generated by Django 6.0.2 on 2026-03-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_place_image_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='town',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
